services:
  dutyroster:
    image: dutyroster-next:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      TZ: Asia/Bangkok
      PGPASSWORD: "Admin@9999"
      # @ ในรหัสผ่านต้อง encode เป็น %40
      DATABASE_URL: "postgresql://postgres:Admin%409999@192.168.50.43:5432/dutyroster"
      SECURE_COOKIES: "false"
    restart: unless-stopped
